default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  database: voting_development
  username: voting_user
  password: 123456
  host: localhost
  port: 5432
test:
  <<: *default
  database: voting_test
  username: voting_user
  password: 123456
  host: localhost
  port: 5432
production:
  <<: *default
  database: voting_production
  username: voting_user
  password: <%= ENV['DFC_DATABASE_PASSWORD'] %>
