# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 69f2cc635d8ba3001f3d6a568dd671f8eacd8fec0adb408173c6c57228572d88604f4700022c553a49265dcbd825ac92912a335b35f7ee4833d8db0fc100f7a1

test:
  secret_key_base: 1dcf5d5bb8a3a21dde91a969d27497222f5e4847116c5661640eaff6824b9d0d17d61e4dff058e75e45e1d4e4f5690eec5ba46991d2bfb9b2ca048d8dbc8d3ff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
